services:
  php:
    build: .
    container_name: symfony_php
    working_dir: /var/www/symfony
    environment:
      HOME: /tmp
      YARN_CACHE_FOLDER: /tmp/.yarn-cache
    volumes:
      - .:/var/www/symfony
    depends_on:
      - mysql
    user: "${UID:-1000}:${GID:-1000}"

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    ports:
      - "3305:3306"

#  db:
#    image: postgres:9.5
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    ports:
#     - 5444:5432

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
